from iso15118.shared.messages.iso15118_2.datatypes import ProfileEntryDetails
from iso15118.shared.messages.datatypes import PVPMax
from iso15118.shared.messages.enums import UnitSymbol
import logging

logger = logging.getLogger(__name__)
'''
    deptime_linear is used to generate a linear power curve
    for a given departure time, energy amount, and maximum power.
'''
def deptime_linear(DepTime: float, EAmount: float, PMax: float) -> tuple[list,list,list]:
    # to distribute power linearly during the requested time
    # DT is in minutes
    # EAmount is in Wh
    # PMax is in W
    num_entries = 24 #TODO: determine how many entries are allowed
    time_interval = DepTime / num_entries

    P = EAmount / (DepTime / 60) # convert Wh to W
    if P > PMax:
        P = PMax  # limit to PMax

    # Create a power curve that is constant over the DepTime without numpy
    Power_curve = [P] * num_entries  # constant power over the DepTime
    Time_vector = []
    for i in range(num_entries):
        Time_vector.append(i * time_interval)

    # Create a state of charge progress vector
    SoC_progress = []
    for j in range(num_entries):
        #time elapsed (in hours) times power (in W) gives us the energy in Wh
        SoC_progress.append((Time_vector[j] /60) * Power_curve[j])

    return SoC_progress, [Power_curve], Time_vector


'''
    formatCurveData takes the output of the charge curve calculation, and formats
    it into a JSON string that will be accepted by Node-RED's `chart`
    module.
    @author Katie
'''
def formatCurveData(profile_entry_list: list[ProfileEntryDetails]) -> dict:
    # Node-RED expects watts & miliseconds
    yc_curve = [{"x": float(ped.start), "y": float(ped.max_power.value)} for ped in profile_entry_list]
    return {
      "series": ["A"],
      "data": [yc_curve],
      "labels": ["r1"]
    }


'''
    generate_new_schedule is used in `evcc/simulator.py`'s `process_sa_schedules_v2` to
    create a profile_entry list from both the existing `secc_schedule` and a schedule
    generated by the above LQR Charging Optimizer 
    @author Katie
'''
def generate_new_schedule(secc_schedule: list[ProfileEntryDetails], uc: list, tc: list,
                            departure_time: float, time_elapsed: float) -> list[ProfileEntryDetails]:
    # time_offset = 24 * # max enteries is 24, so refresh every <24 -ish seconds?
    # Define some helper functions...
    # Evenly sample from the `curve_schedule`< up to the end timestamp
    def sample_schedule(schedule: list[tuple[float, float]]) -> list[tuple[float, float]]:
        sliced_array = [x for x in schedule if (time_elapsed <= x[1])]
        return sliced_array[0:23]

    # Generates a ProfileEntryDetails obj for the final schedule
    def make_entry(val: float, timestamp: float, next_ts: float) -> ProfileEntryDetails:
        # Create the ProfileEntryDetails...
        return  ProfileEntryDetails(
            start=int(timestamp),
            max_power=PVPMax(
                multiplier=0,
                value=val, # Convert miliwattsHours to WattHours
                unit=UnitSymbol.WATT
            ),
            max_phases_in_use = None
        )

    def convert_tuple_schedule(curve_arr: list[tuple[float, float]]) -> list[ProfileEntryDetails]:
        schedule_arr = []
        for i in range(0, len(curve_arr) - 2):
            schedule_arr.append(make_entry(curve_arr[i][0], curve_arr[i][1], curve_arr[i+1][1]))
        logger.debug('Done converting tuple schedule')
        if (len(schedule_arr)):
            schedule_arr.pop(-1)

        return (schedule_arr)

    curve_schedule = [(x,y) for x, y, in zip(uc[0], tc)]
    # We get 24 from ISO 15118-2, Table 71.  This is the max number of profile enteries.
    # For some reason, EVerest only accepts 23... Investigate later
    curve_schedule = sample_schedule(curve_schedule)

    if (len(curve_schedule) <= 2): # Check to see if we're done...
        logger.debug("Done with profile, defaulting to SECC Schedule")
        return secc_schedule

    curve_schedule = convert_tuple_schedule(curve_schedule)
    logger.debug(f"Returning a curve schedule of: {curve_schedule}")

    return curve_schedule
